spring.profiles.active=@activatedProperties@


#server.port=8080

spring.datasource.username=${db_username}
spring.datasource.password=${db_password}

# HikariCP connection pool settings
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
spring.servlet.multipart.location=${file_upload_tmp}
file.upload.base-path=${file_upload}

spring.web.resources.static-locations=classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:///${file_upload}


spring.http.encoding.enabled=true

server.tomcat.max-swallow-size=-1
server.servlet.session.timeout=60m